# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: James Routley
email: jroutley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about programming and food.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamesroutley.co.uk" # the base hostname & protocol for your site

# SEO settings
twitter:
  username: james_routley
author: james_routley
social:
  name: James Routley
  links:
    - https://twitter.com/james_routley
    - https://github.com/jamesroutley
    - https://www.linkedin.com/in/james-routley-ab928ba8/
    - https://keybase.io/jamesroutley

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - venv
  - vendor
sass:
  style: compressed

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
